#ifndef _ERROR_H
#define _ERROR_H

enum Error
{
    ERROR_DATA_LOGGER = 1,
    ERROR_IST_8310,
    ERROR_MPU_6050,
    ERROR_MADGWICK,
    ERROR_IMU,
    ERROR_STATS,
    ERROR_FLIGHT_COMPUTER,
    ERROR_LOOP_CONTROLLER,
    ERROR_IO,
};

#endif // _ERROR_H