#ifndef _WEB_MESSAGE_TYPE_H
#define _WEB_MESSAGE_TYPE_H

#include <Arduino.h>

enum WebMessageType : uint8_t
{
    WEB_MESSAGE_UNKNOWN = 0,
    HELLO_ROCKET_MESSAGE_TYPE,
    HELLO_CONTROL_CENTER_MESSAGE_TYPE,

    // Launch-Pad
    LAUNCH_PAD_START_MESSAGE_TYPE,
    LAUNCH_PAD_ABORT_MESSAGE_TYPE,
    LAUNCH_PAD_STATUS_MESSAGE_TYPE,

    LAUNCH_PAD_CONFIG_MESSAGE_TYPE,
    REQUEST_LAUNCH_PAD_CONFIG_MESSAGE_TYPE,

    // Rocket
    ROCKET_START_MESSAGE_TYPE,
    ROCKET_ABORT_MESSAGE_TYPE,
    ROCKET_UNLOCK_MESSAGE_TYPE,

    ROCKET_OPEN_PARACHUTE_MESSAGE_TYPE,
    ROCKET_CLOSE_PARACHUTE_MESSAGE_TYPE,

    ROCKET_STATUS_MESSAGE_TYPE,
    ROCKET_TELEMETRY_MESSAGE_TYPE,

    ROCKET_CONFIG_MESSAGE_TYPE,
    REQUEST_ROCKET_CONFIG_MESSAGE_TYPE,
};

#endif // _WEB_MESSAGE_TYPE_H
