#ifndef _LAUNCH_COMPUTER_STATE_H
#define _LAUNCH_COMPUTER_STATE_H

enum LaunchComputerState
{
    LAUNCH_COMPUTER_LOCKED,

    LAUNCH_COMPUTER_STARTUP,
    LAUNCH_COMPUTER_WAIT_FOR_ROCKET,

    LAUNCH_COMPUTER_PRESSURISING,
    LAUNCH_COMPUTER_WAIT_FOR_PRESSURE,

    LAUNCH_COMPUTER_WAIT_TANK_CHILL,

    LAUNCH_COMPUTER_ROCKET_STARTUP,
    LAUNCH_COMPUTER_WAIT_ROCKET_STARTUP,

    LAUNCH_COMPUTER_LAUNCH_COUNTDOWN,
    LAUNCH_COMPUTER_LAUNCH,

    LAUNCH_COMPUTER_WAIT_LIFT_OFF,

    LAUNCH_COMPUTER_ABORT_AFTER_LAUNCH,
    LAUNCH_COMPUTER_ABORT_ROCKET_ERROR,
    LAUNCH_COMPUTER_ABORT_CONNECTION_LOST,
};

#endif // _LAUNCH_COMPUTER_STATE_H