#ifndef _LAUNCH_COMPUTER_STATE_H
#define _LAUNCH_COMPUTER_STATE_H

enum LaunchComputerState
{
    LAUNCH_COMPUTER_LOCKED,
    LAUNCH_COMPUTER_STARTUP,
    LAUNCH_COMPUTER_PRESSURISING,
    LAUNCH_COMPUTER_TANK_CHILL,
    LAUNCH_COMPUTER_LAUNCH,
    LAUNCH_COMPUTER_ABORT_AFTER_LAUNCH,
};

#endif // _LAUNCH_COMPUTER_STATE_H