name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        working-directory: ./website
        with:
          node-version: '14'
          check-latest: true

      - run: npm ci
      - run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/dist
          full_commit_message: ${{ github.event.head_commit.message }}

      - uses: actions/upload-artifact@v2
        with:
          name: rocket-dist
          path: ./website/dist